AllCops:
  Include:
    - "**/*.rb"
  Exclude:
    - ".git/**/*"
    - "db/**/*"
    - "node_modules/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
  NewCops: disable
  SuggestExtensions: false

# TODO: disabled to make current codebase pass.
#       we may want to revisit these at some point.
Layout/FirstArgumentIndentation:
  Enabled: false
Layout/FirstHashElementIndentation:
  Enabled: false
Layout/LineLength:
  Enabled: false
Lint/MissingSuper:
  Exclude:
    - "app/components/**/*.rb"
    - "app/policies/**/*.rb"
    - "app/services/**/*.rb"
Lint/ImplicitStringConcatenation:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Naming/PredicateName:
  Enabled: false
Naming/VariableNumber:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/HashLikeCase:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/NegatedIf:
  Enabled: false
Style/RedundantRegexpEscape:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  Enabled: false
