name: Run tests
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: app_test
        ports:
          - 5432:5432
        options: >-
          --mount type=tmpfs,destination=/var/lib/postgresql/data
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_ASSET_HOST: http://example.com
          envkey_DEFAULT_EMAIL: info@example.com
          envkey_POSTGRES_PASSWORD: postgres
          envkey_RAILS_ENV: test
          envkey_RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
          envkey_SITE_URL: http://example.com
      - name: Build docker images
        run: docker-compose build
      - name: Install packages
        run: |
          docker-compose run app bundle install
          docker-compose run app yarn install
      - name: Setup database
        run: docker-compose run app bin/rails db:setup
      - name: Compile assets
        run: docker-compose run app bin/rails assets:precompile
      - name: Run Rubocop
        run: docker-compose run app bundle exec rubocop
      - name: Run tests
        run: docker-compose run app bin/rspec